spring:
  application:
    name: spring-ai-mcp-server
  profiles:
    active: dev
  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource      # 数据源的类型，可以更改为其他的数据源配置，比如druid
    driver-class-name: com.mysql.cj.jdbc.Driver      # mysql/MariaDB 的数据库驱动类名称
    url: jdbc:mysql://${MYSQL_AUTH_URI}/springai-items-mcp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_AUTH_USER}
    password: ${MYSQL_AUTH_PASS}
    hikari:
      pool-name: DataSourceHikariCP           # 连接池的名字
      connection-timeout: 30000               # 等待连接池分配连接的最大时间（毫秒），超过这个时长还没有可用的连接，则会抛出SQLException
      minimum-idle: 5                         # 最小连接数
      maximum-pool-size: 20                   # 最大连接数
      auto-commit: true                       # 自动提交
      idle-timeout: 600000                    # 连接超时的最大时长（毫秒），超时则会被释放（retired）
      max-lifetime: 18000000                  # 连接池的最大生命时长（毫秒），超时则会被释放（retired）
      connection-test-query: SELECT 1

  ai:
    mcp:
      server:
        name: spring-ai-mcp-server-sse # MCP服务器名称
        version: 1.0.0 # 服务器版本号
        sse-endpoint: /sse
        type: async
  mail:
    host: smtp.qq.com               # QQ 邮箱 SMTP 服务器
    port: 587                       # 端口号465或587，改为 587 端口，更稳定
    username: ${MAIL_QQ_AUTH_USER}
    password: ${MAIL_QQ_AUTH_CODE}       # 不是登录密码，而是「授权码」（16 位字母数字组合）
    protocol: smtp                  # 改为 smtp
    default-encoding: UTF-8
    properties:
      debug: true  # 调试模式，便于排查问题
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
#          auth: true                # 必须显式开启认证
          timeout: 5000              # 超时时间

logging:
  level:
    root: info

# MyBatisPlus 的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置MyBatis日志实现类，使用标准输出打印SQL语句
  global-config:
    db-config:
      id-type: assign_id      # 主键生成策略：使用assign_id方式生成分布式ID
      update-strategy: not_empty  # 更新策略：只更新非空字段
  mapper-locations: classpath*:/mappers/*.xml  # Mapper XML文件路径配置

