spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
    vectorstore:
      redis:
        initialize-schema: true  # 是否初始化所需的模式， 如出现 404 错误, 需要手动创建索引
        index-name: lee-vectorstore  # 用于存储向量的索引名称
        prefix: 'embedding:'  # Redis 键的前缀
  data:
    redis:
      host: 192.168.56.101
      port: 6379
      password: redis123
#      database: 0

logging:
  level:
    root: info
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.ai.vectorstore: TRACE
    org.springframework.ai.embedding: TRACE
