spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      ## 首次调用API： https://api-docs.deepseek.com/zh-cn/
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

logging:
  level:
    root: info