spring:
  application:
    name: spring-ai-mcp-client
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
      embedding:
        options:
          model: text-embedding-v2
#    embedding:
#      transformer:
#        tokenizer:
#          uri: classpath:/onnx/all-MiniLM-L6-v2/tokenizer.json
#        onnx:
#          modelUri: classpath:/onnx/all-MiniLM-L6-v2/model.onnx
#          modelOutputName: token_embeddings
#        cache:
#          enabled: true
#          directory: file:/onnx
    vectorstore:
      redis:
        # 必须启动时候自动创建'索引', 不然会出现查询不到数据等问题
        initialize-schema: true
        index-name: lee-vectorstore
        prefix: 'embedding:'
  data:
    redis:
      host: 192.168.56.101
      port: 6379
      password: redis123
      timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

logging:
  level:
    root: info
    org.springframework.ai: TRACE
    org.springframework.ai.transformer: TRACE
    ai.onnxruntime: TRACE